function import_phytoplankton_Species_Staging()
    run('../../../../actions/csiem_data_paths.m')

    main_dir = [datapath,'data-lake/WCWA/PLOOM/Phyto/30/December99.xls'];
    
    outdir = [datapath,'data-warehouse/csv_holding/wcwa/ploom/phy/species/30/'];
    inputfile = main_dir;

    if ~exist(outdir,'dir')
        mkdir(outdir);
    else
        delete([outdir,'*.csv'])
    end

    SheetString = 'Sheet2';
    DateStr = '1999-12-06 00:00:00';
    SiteIndexes = [6,9,12];
    SiteNames = {'200N', '200S', 'O'};
    SheetTable = importfile(inputfile,SheetString, [3,300]);
    maxTableHeight = 146;
        StageFromSheetTable(SheetTable,DateStr,SiteIndexes,outdir,maxTableHeight,SiteNames);

end

function StageFromSheetTable(SheetTable,DateStr,SiteIndexes,outdir,maxTableHeight,SiteNames)
    for  siteNum = 1:length(SiteIndexes)
        siteIndex = SiteIndexes(siteNum);
        i=1;

        while i <= maxTableHeight-2
            Varname = SheetTable{i,1}{1};
            if strcmp('Total',Varname)
                %this is when the table has Group data so skip 3 rows (total, the empty and the next name row)
                i = i+3;
                continue
            end
            CellConcentration = SheetTable{i,siteIndex};
            fname = sprintf("%s%s_%s.csv",outdir,Varname,SiteNames{siteNum});
            fid = fopen(fname,'a+');
            fprintf(fid,"%s,0,%f,N\n",DateStr,CellConcentration);
            fclose(fid);
            i = i+1;
        end
        
    end
end




function AllNorthS6 = importfile(workbookFile, sheetName, dataLines)
    %IMPORTFILE Import data from a spreadsheet
    %  ALLNORTHS6 = IMPORTFILE(FILE) reads data from the first worksheet in
    %  the Microsoft Excel spreadsheet file named FILE.  Returns the data as
    %  a table.
    %
    %  ALLNORTHS6 = IMPORTFILE(FILE, SHEET) reads from the specified
    %  worksheet.
    %
    %  ALLNORTHS6 = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
    %  specified worksheet for the specified row interval(s). Specify
    %  DATALINES as a positive scalar integer or a N-by-2 array of positive
    %  scalar integers for dis-contiguous row intervals.
    %
    %  Example:
    %  AllNorthS6 = importfile("C:\Users\loxte\Downloads\Wamsi 13_08_2024\Phyto\WaterCorp\All North.xls", "240699", [26, 56]);
    %
    %  See also READTABLE.
    %
    % Auto-generated by MATLAB on 13-Sep-2024 16:48:49
    
    %% Input handling
    
    % If no sheet is specified, read first sheet
    if nargin == 1 || isempty(sheetName)
        sheetName = 1;
    end
    
    % If row start and end points are not specified, define defaults
    if nargin <= 2
        dataLines = [26, 56];
    end
    
    %% Set up the Import Options and import the data
    opts = spreadsheetImportOptions("NumVariables", 19);
    
    % Specify sheet and range
    opts.Sheet = sheetName;
    opts.DataRange = "A" + dataLines(1) + ":S" + dataLines(2);
    
    % Specify column names and types
    opts.VariableNames = ["Taxon","t1","t2","N1-Total","N1-%","N1-Cells/ml","N2-Total","N2-%", "N2-Cells/ml",	"N3-Total",	"N3-%",	"N3-Cells/ml","N4-Total","N4-%","N4-Cells/ml","t3","t4","t5","t6"];
    opts.VariableTypes = ["char", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double","double","double","double","double","double"];
    
    % Specify variable properties
 
    opts = setvaropts(opts, opts.VariableNames, "EmptyFieldRule", "auto");
    
    % Import the data
    AllNorthS6 = readtable(workbookFile, opts, "UseExcel", false);
    
end
