function Untitled = ReadInCoordDictionary(filename, dataLines)
%IMPORTFILE Import data from a text file
%  UNTITLED = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  UNTITLED = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  Untitled = importfile("C:\Users\loxte\Desktop\WAMSI_WORK\Current_Data\WWMSP3.1 - Sediment Quality\Study areas and site locations\3.1_coordinates_edited.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 07-Feb-2024 10:09:43

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 10, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Title", "Latitude", "Longitude", "Var7", "Var8", "Var9", "Var10"];
opts.SelectedVariableNames = ["Title", "Latitude", "Longitude"];
opts.VariableTypes = ["string", "string", "string", "string", "double", "double", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Title", "Var7", "Var8", "Var9", "Var10"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Title", "Var7", "Var8", "Var9", "Var10"], "EmptyFieldRule", "auto");

% Import the data
Untitled = readtable(filename, opts);
tempArray = table2array(Untitled(:,'Title'));
ind = contains(tempArray," ");
for i = 1:length(tempArray)
    if ind(i) == 1
        trimmed = char(tempArray(i));
        bloated = true;
        while bloated == true
            trimmed = trimmed(1:end-1);
            if trimmed(end) ~= " "
                bloated = false;
            end
        end
        tempArray(i) = string(trimmed);
    end

end

Untitled(:,'Title') = array2table(tempArray);
% LocationNameColVec = Untitled.Title;
% LocationLatColVec = Untitled.Latitude;
% LocationLongColVec = Untitled.Longitude;

end