function import_phytoplankton_31_Group_Staging()
    run('../../../../actions/csiem_data_paths.m')

    main_dir = [datapath,'data-lake/WCWA/PLOOM/Phyto/32/March 2000.xls'];
    outdir = [datapath,'data-warehouse/csv_holding/wcwa/ploom/phy/group/32/'];
    inputfile = main_dir;

    if ~exist(outdir,'dir')
        mkdir(outdir);
    else
        delete([outdir,'*.csv'])
    end

    SheetString = 'Sheet2';
    DateStr = '2000-3-26 00:00:00';
    SiteIndexes = [7,11,15];
    SiteNames = {'200N', '200S', 'O'};
    SheetTable = importfile(inputfile,SheetString, [2,300]);
    TableSize = 165;
        StageFromSheetTableRunningCount(SheetTable,DateStr,SiteIndexes,outdir,TableSize,SiteNames);

end

function StageFromSheetTableRunningCount(SheetTable,DateStr,SiteIndexes,outdir,TableSize,SiteNames)
    for  siteNum = 1:length(SiteIndexes)
        siteIndex = SiteIndexes(siteNum);

        %init GroupName
        i=1;
        Varname = SheetTable{i,1}{1};
        i=2; %get first data values
        RunningTotal = 0;
        while i <= TableSize
            speciesName = SheetTable{i,1}{1};
            if strcmp('Total',speciesName)
                %this is when the table has Group data so skip 3 rows (total, the empty and the next name row)
                % running total should now include all species so print it to a txt file

                fname = sprintf("%s%s_%s.csv",outdir,Varname,SiteNames{siteNum});
                fid = fopen(fname,'a+');
                fprintf(fid,"%s,0,%f,N\n",DateStr,RunningTotal);
                fclose(fid);

                %skip 2 rows and reset running total and grab new Name 
                i = i+2;
                Varname = SheetTable{i,1}{1}; % grab new name
                i = i + 1; %move to next species
                RunningTotal = 0;
                continue
            end
            RunningTotal = sum([RunningTotal,SheetTable{i,siteIndex}],2,'omitnan');
            i = i+1;
        end
        
    end
end




function AllNorthS6 = importfile(workbookFile, sheetName, dataLines)
    %IMPORTFILE Import data from a spreadsheet
    %  ALLNORTHS6 = IMPORTFILE(FILE) reads data from the first worksheet in
    %  the Microsoft Excel spreadsheet file named FILE.  Returns the data as
    %  a table.
    %
    %  ALLNORTHS6 = IMPORTFILE(FILE, SHEET) reads from the specified
    %  worksheet.
    %
    %  ALLNORTHS6 = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
    %  specified worksheet for the specified row interval(s). Specify
    %  DATALINES as a positive scalar integer or a N-by-2 array of positive
    %  scalar integers for dis-contiguous row intervals.
    %
    %  Example:
    %  AllNorthS6 = importfile("C:\Users\loxte\Downloads\Wamsi 13_08_2024\Phyto\WaterCorp\All North.xls", "240699", [26, 56]);
    %
    %  See also READTABLE.
    %
    % Auto-generated by MATLAB on 13-Sep-2024 16:48:49
    
    %% Input handling
    
    % If no sheet is specified, read first sheet
    if nargin == 1 || isempty(sheetName)
        sheetName = 1;
    end
    
    % If row start and end points are not specified, define defaults
    if nargin <= 2
        dataLines = [26, 56];
    end
    
    %% Set up the Import Options and import the data
    opts = spreadsheetImportOptions("NumVariables", 19);
    
    % Specify sheet and range
    opts.Sheet = sheetName;
    opts.DataRange = "A" + dataLines(1) + ":S" + dataLines(2);
    
    % Specify column names and types
    opts.VariableNames = ["Taxon","t1","t2","N1-Total","N1-%","N1-Cells/ml","N2-Total","N2-%", "N2-Cells/ml",	"N3-Total",	"N3-%",	"N3-Cells/ml","N4-Total","N4-%","N4-Cells/ml","t3","t4","t5","t6"];
    opts.VariableTypes = ["char", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double","double","double","double","double","double"];
    
    % Specify variable properties
 
    opts = setvaropts(opts, opts.VariableNames, "EmptyFieldRule", "auto");
    
    % Import the data
    AllNorthS6 = readtable(workbookFile, opts, "UseExcel", false);
    
end
