function create_marvl_config_information

load varkey.mat;

csiem_data_paths

allvars = fieldnames(varkey);

matdir = [datapath,'data-warehouse/mat/agency/'];

filelist = dir(fullfile(matdir, '**/*.mat'));  %get list of files and folders in any subfolder
filelist = filelist(~[filelist.isdir]);  %remove folders from list

fid = fopen('marvl_information.m','wt');

fprintf(fid,'master.fielddata_files = {');

for i = 1:length(filelist)
    fprintf(fid,'''%s'',',regexprep(filelist(i).name,'.mat',''));
end
fprintf(fid,'};');

fprintf(fid,'\n');
fprintf(fid,'master.varname = {...\n');

vars = [];
for i = 1:length(filelist)
    filename = [filelist(i).folder,'/',filelist(i).name]
    load(filename);
    sites = fieldnames(csiem);
    for j = 1:length(sites)
        thevars = fieldnames(csiem.(sites{j}));
        vars = [vars;thevars];
    end
end
clear csiem;
uvars = unique(vars);
for i = 1:length(uvars)
    for j = 1:length(allvars)
        if strcmpi(uvars{i},varkey.(allvars{j}).tfvName) == 1
            fprintf(fid,'''%s'',''%s'';...\n',uvars{i},varkey.(allvars{j}).Name);
        end
    end
end
fprintf(fid,'};');
fprintf(fid,'\n');
fprintf(fid,'\n');

fprintf(fid,'timeseries.start_plot_ID = 1;\n');
fprintf(fid,'timeseries.end_plot_ID = %d;\n',length(uvars));

% timeseries.start_plot_ID = 2;
% timeseries.end_plot_ID = 18;

% master.varname = {...
%      'H','H';...
%     'SAL','Salinity';...
%      'TEMP','Temperature';...
%     'WQ_OXY_OXY','DO';...
%     'WQ_DIAG_TOT_TN','TN';...
%     'WQ_DIAG_TOT_TP','TP';...
%     'WQ_DIAG_OXY_SAT','DO-saturation';...
%     'WQ_NIT_AMM','NH_4';...
%     'WQ_NIT_NIT','NO_3';...
%     'WQ_PHS_FRP','PO_4';...
%     'WQ_OGM_POP','POP';...
%     'WQ_OGM_DOP','DOP';...
%     'WQ_OGM_PON','PON';...
%     'WQ_OGM_DON','DON';...
%     'WQ_OGM_POC','POC';...
%     'WQ_OGM_DOC','DOC';...
%     'WQ_PHS_FRP_ADS','FRPADS';...
%     'WQ_DIAG_PHY_TCHLA','TCHLA';...
%     'WQ_DIAG_TOT_TSS','TSS';...
%     'WQ_DIAG_TOT_TOC','TOC';...
%     'WQ_OGM_DOC','DOC';...
%     'WQ_DIAG_TOT_TURBIDITY','Turbidity';...
%     'WQ_NCS_SS1','SS1';...
%     'WQ_PHY_DINO','DINO';...
%     'WQ_PHY_MDIAT','MDIAT';...
%     'WQ_PHY_CRYPT','CRYPT';...
%     'WQ_PHY_BGA','BGA';...
%     'WQ_PHY_GRN','GRN';...
%     'WQ_DIAG_TOT_LIGHT','TOT-LIGHT';...
%     'WQ_DIAG_TOT_PAR','TOT-PAR';...
%     'WQ_DIAG_TOT_UV','TOT-UV';...
%     'WQ_DIAG_TOT_EXTC','TOT-EXTC';...
% 	'WQ_DIAG_OGM_PON_SWI','PONSWI';...
%     'WQ_DIAG_OGM_DON_SWI','DONSWI';...
%     'WQ_DIAG_NIT_AMM_DSF','AMMDSF';...
%     'WQ_DIAG_NIT_NIT_DSF','NITDSF';...
%     'WQ_DIAG_OGM_POP_SWI','POPSWI';...
%     'WQ_DIAG_OGM_DOP_SWI','DOPSWI';...
%     'WQ_DIAG_PHS_FRP_DSF','FRPDSF';...
%     };

% fclose(fid);