master.fielddata_files = {'csiem_BMT_public','csiem_BOM_public','csiem_CSMC_public','csiem_DOT_public','csiem_DPIRD_public','csiem_DWER_public','csiem_FPA_public','csiem_IMOS_public','csiem_WAMSI_public','csiem_WCWA_public',};
master.varname = {...
'ACCELERATIONX','ACCELERATIONX';...
'ACCELERATIONY','ACCELERATIONY';...
'ACCELERATIONZ','ACCELERATIONZ';...
'AIRTEMP','Air Temperature';...
'AMPLITUDE1','AMPLITUDE1';...
'AMPLITUDE2','AMPLITUDE2';...
'AMPLITUDE3','AMPLITUDE3';...
'Allo','Allo';...
'AlphaBetaCar','AlphaBetaCar';...
'Anth','Anth';...
'Asta','Asta';...
'Butfuco','Butfuco';...
'COND','Specific Conductivity';...
'Cantha','Cantha';...
'CphlA','CphlA';...
'CphlB','CphlB';...
'CphlC1','CphlC1';...
'CphlC2','CphlC2';...
'CphlC3','CphlC3';...
'CphlideA','CphlideA';...
'D','Depth';...
'DENSITY_ANOMALY','DENSITY ANOMALY';...
'DIC','Dissolved Inorganic Carbon';...
'Diadchr','Diadchr';...
'Diadino','Diadino';...
'Diato','Diato';...
'Dino','Dino';...
'DvCphlA','DvCphlA';...
'DvCphlA_CphlA','DvCphlA+CphlA';...
'DvCphlB','DvCphlB';...
'DvCphlB_CphlB','DvCphlB+CphlB';...
'Echin','Echin';...
'FLOW','Daily Discharge';...
'Fluorescence_V','Fluorescence';...
'Fuco','Fuco';...
'Gyro','Gyro';...
'H','Stage Height';...
'H','Water Surface Height';...
'HEADING','HEADING';...
'Hexfuco','Hexfuco';...
'Ketohexfuco','Ketohexfuco';...
'Lut','Lut';...
'Lyco','Lyco';...
'MAX_WIND_SPEED','Wind Speed (max)';...
'MgDvp','MgDvp';...
'Neo','Neo';...
'Nitrite','Nitrite';...
'ON','Organic Nitrogen';...
'OP','Organic Phosphorus';...
'PAR_STD','Surface Photosynthetically Active Photon Flux (std)';...
'PITCH','Pitch';...
'PRECIP','Precipitation';...
'PRESSURE','PRESSURE';...
'PRESSURE_SENSOR_DEPTH','PRESSURE_SENSOR_DEPTH';...
'Perid','Perid';...
'PhideA','PhideA';...
'PhytinA','PhytinA';...
'PhytinB','PhytinB';...
'Picoeukaryotes','Picoeukaryotes';...
'Pras','Pras';...
'Prochlorococcus','Prochlorococcus';...
'PyrophideA','PyrophideA';...
'PyrophytinA','PyrophytinA';...
'RELHUM','Relative Humidity';...
'ROLL','ROLL';...
'SAL','Salinity';...
'SECCHI_DEPTH','Secchi Depth';...
'SPEED_OF_SOUND','SPEED_OF_SOUND';...
'Synechococcus','Synechococcus';...
'TEMP','Temperature';...
'TPAR','Daily Surface Photosynthetically Active Photon Flux';...
'TSOLAR','Daily Solar Irradiance';...
'TSSinorganic','TSSinorganic';...
'TSSorganic','TSSorganic';...
'Tilt','Tilt';...
'Total_Par_day','Daily Photosynthetically Active Photon Flux';...
'UCUR','UCUR (eastward velocity)';...
'VCUR','VCUR (northward velocity)';...
'Viola','Viola';...
'WCUR','WCUR';...
'WL_398_uW','Spectral Radiative Flux (WL - 398µW)';...
'WL_398_umol','Spectral Photon Flux (WL - 398µmol)';...
'WL_448_uW','Spectral Radiative Flux (WL - 448µW)';...
'WL_448_umol','Spectral Photon Flux (WL - 448µmol)';...
'WL_470_uW','Spectral Radiative Flux (WL - 470µW)';...
'WL_470_umol','Spectral Photon Flux (WL - 470µmol)';...
'WL_524_uW','Spectral Radiative Flux (WL - 524µW)';...
'WL_524_umol','Spectral Photon Flux (WL - 524µmol)';...
'WL_554_uW','Spectral Radiative Flux (WL - 554µW)';...
'WL_554_umol','Spectral Photon Flux (WL - 554µmol)';...
'WL_590_uW','Spectral Radiative Flux (WL - 590µW)';...
'WL_590_umol','Spectral Photon Flux (WL - 590µmol)';...
'WL_628_uW','Spectral Radiative Flux (WL - 628µW)';...
'WL_628_umol','Spectral Photon Flux (WL - 628µmol)';...
'WL_656_uW','Spectral Radiative Flux (WL - 656µW)';...
'WL_656_umol','Spectral Photon Flux (WL - 656µmol)';...
'WL_699_uW','Spectral Radiative Flux (WL - 699µW)';...
'WL_699_umol','Spectral Photon Flux (WL - 699µmol)';...
'WQ_CAR_PH','pH';...
'WQ_DIAG_MAC_PAR','Photosynthetically Active Radiation';...
'WQ_DIAG_OAS_IRR_BAND_1','Spectral Radiative Flux (WL - 410W)';...
'WQ_DIAG_OAS_IRR_BAND_2','Spectral Radiative Flux (WL - 440W)';...
'WQ_DIAG_OAS_IRR_BAND_3','Spectral Radiative Flux (WL - 490W)';...
'WQ_DIAG_OAS_IRR_BAND_4','Spectral Radiative Flux (WL - 510W)';...
'WQ_DIAG_OAS_IRR_BAND_5','Spectral Radiative Flux (WL - 550W)';...
'WQ_DIAG_OAS_IRR_BAND_6','Spectral Radiative Flux (WL - 590W)';...
'WQ_DIAG_OAS_IRR_BAND_7','Spectral Radiative Flux (WL - 635W)';...
'WQ_DIAG_OAS_IRR_BAND_8','Spectral Radiative Flux (WL - 660W)';...
'WQ_DIAG_OAS_IRR_BAND_9','Spectral Radiative Flux (WL - 700W)';...
'WQ_DIAG_OXY_SAT','O2 Saturation';...
'WQ_DIAG_PHY_TCHLA','Chlorophyll-a';...
'WQ_DIAG_TOT_PAR','Photosynthetically Active Photon Flux';...
'WQ_DIAG_TOT_TKN','Total Kjeldahl Nitrogen';...
'WQ_DIAG_TOT_TN','Total Nitrogen';...
'WQ_DIAG_TOT_TP','Total Phosphorus';...
'WQ_DIAG_TOT_TSS','Total Suspended Solids';...
'WQ_DIAG_TOT_TURBIDITY','Turbidity';...
'WQ_NIT_AMM','Ammonium';...
'WQ_NIT_NIT','Nitrate';...
'WQ_OGM_DOC','Dissolved Organic Carbon';...
'WQ_OGM_DON','Dissolved Organic Nitrogen';...
'WQ_OGM_POC','Particulate Organic Carbon';...
'WQ_OXY_OXY','Dissolved Oxygen';...
'WQ_PHS_FRP','Filterable Reactive Phosphate';...
'WQ_SIL_RSI','Reactive Silica';...
'WVDIR','Peak Wave Direction';...
'WVHT','Significant Wave Height';...
'WVPER','Peak Wave Period';...
'Zea','Zea';...
'density','Density';...
'fluorescence','Fluorescence';...
'light_attenuation_coefficient','Light Attenuation Coefficient';...
'logger_temperature','Logger Temperature';...
'max_PAR','Surface Photosynthetically Active Photon Flux (max)';...
'max_solar_raditation','Surface Solar Irradiance (max)';...
'max_station_level_pressure','Station Level Pressure (max)';...
'mean_solar_raditation','Surface Solar Irradiance';...
'min_PAR','Surface Photosynthetically Active Photon Flux (min)';...
'min_solar_raditation','Surface Solar Irradiance (min)';...
'min_station_level_pressure','Station Level Pressure (min)';...
'min_wind_speed','Wind Speed (min)';...
'phaeophytin_a','Phaeophytin-a';...
'posidonia_sinuosa_above_ground_biomass','Posidonia Sinuosa Above Ground Biomass';...
'posidonia_sinuosa_below_ground_biomass','Posidonia Sinuosa Below Ground Biomass';...
'posidonia_sinuosa_count','Posidonia Sinuosa Count';...
'posidonia_sinuosa_dry_weight','Posidonia Sinuosa Dry Weight';...
'posidonia_sinuosa_total_biomass','Posidonia Sinuosa Total Biomass';...
'sea_level_pressure_std','Station Level Pressure (std)';...
'solar_raditation_std','Surface Solar Irradiance (std)';...
'surface_photosynthetically_active_photon_flux','Surface Photosynthetically Active Photon Flux';...
'wind_direction_std','Wind Direction (std)';...
};

timeseries.start_plot_ID = 1;
timeseries.end_plot_ID = 150;
