master.fielddata_files = {'csiem_AIMS_public','csiem_BMT_public','csiem_BOM_public','csiem_CSIRO_public','csiem_CSMC_public','csiem_DEP_public','csiem_DOT_public','csiem_DPIRD_public','csiem_DWER_public','csiem_ESA_public','csiem_FPA_public','csiem_IMOS_public','csiem_IMOS_public_Yvette','csiem_MOI_public','csiem_NASA_public','csiem_NASA_public_Yvette','csiem_UWA_public','csiem_UWA_public_Yvette','csiem_WAMSI_public','csiem_WAMSI_public_Yvette','csiem_WCWA_public',};
master.varname = {...
'ACCELERATIONX','ACCELERATIONX';...
'ACCELERATIONY','ACCELERATIONY';...
'ACCELERATIONZ','ACCELERATIONZ';...
'AIRTEMP','Air Temperature';...
'AIRTEMP_DEW','Dew Point Temperature';...
'AIRTEMP_WET','Wet Bulb Air Temperature';...
'AMPLITUDE1','AMPLITUDE1';...
'AMPLITUDE2','AMPLITUDE2';...
'AMPLITUDE3','AMPLITUDE3';...
'Allo','Allo';...
'AlphaBetaCar','AlphaBetaCar';...
'Anth','Anth';...
'Asta','Asta';...
'BBP','Backscattering Coefficient';...
'Butfuco','Butfuco';...
'CLOUD','Cloud Cover';...
'COND','Specific Conductivity';...
'CONDUCTIVITY','Actual Conductivity';...
'Cantha','Cantha';...
'CphlA','CphlA';...
'CphlB','CphlB';...
'CphlC1','CphlC1';...
'CphlC2','CphlC2';...
'CphlC3','CphlC3';...
'CphlideA','CphlideA';...
'D','Depth';...
'DENSITY_ANOMALY','DENSITY ANOMALY';...
'Diadchr','Diadchr';...
'Diadino','Diadino';...
'Diato','Diato';...
'Dino','Dino';...
'DvCphlA','DvCphlA';...
'DvCphlB','DvCphlB';...
'Echin','Echin';...
'Fluorescence_V','Fluorescence';...
'Fuco','Fuco';...
'GREEN','Green Algae';...
'Gyro','Gyro';...
'H','Stage Height';...
'H','Water Surface Height';...
'HAPTO','Haptophytes';...
'HEADING','HEADING';...
'Hexfuco','Hexfuco';...
'KD490','Diffuse Attenuation Coefficient at 490nm';...
'Ketohexfuco','Ketohexfuco';...
'Lut','Lut';...
'Lyco','Lyco';...
'MAX_WIND_SPEED','Wind Speed (max)';...
'MICRO','Microplankton';...
'MSLP','Station Level Pressure';...
'MSLP_max','Station Level Pressure (max)';...
'MSLP_min','Station Level Pressure (min)';...
'MSLP_std','Station Level Pressure (std)';...
'MgDvp','MgDvp';...
'NANO','Nanoplankton';...
'Neo','Neo';...
'Nitrite','Nitrite';...
'ON','Organic Nitrogen';...
'OP','Organic Phosphorus';...
'PAR','Photosynthetically Active Photon Flux';...
'PAR_sf_max','Surface Photosynthetically Active Photon Flux (max)';...
'PAR_sf_min','Surface Photosynthetically Active Photon Flux (min)';...
'PAR_sf_std','Surface Photosynthetically Active Photon Flux (std)';...
'PIC','Particulate Inorganic Carbon';...
'PICO','Picoplankton';...
'PITCH','Pitch';...
'PP','Primary Production';...
'PRECIP','Precipitation';...
'PRESSURE','PRESSURE';...
'PRESSURE_SENSOR_DEPTH','PRESSURE_SENSOR_DEPTH';...
'PROCHLO','Prochlorococcus';...
'PROKAR','Prokaryotes';...
'Perid','Perid';...
'PhideA','PhideA';...
'PhytinA','PhytinA';...
'PhytinB','PhytinB';...
'Picoeukaryotes','Picoeukaryotes';...
'Pras','Pras';...
'Prochlorococcus','Prochlorococcus';...
'PyrophideA','PyrophideA';...
'PyrophytinA','PyrophytinA';...
'RELHUM','Relative Humidity';...
'RHOW','Density';...
'ROLL','ROLL';...
'RRS412','RS reflectance at 412nm';...
'RRS443','RS reflectance at 443nm';...
'RRS490','RS reflectance at 490nm';...
'RRS555','RS reflectance at 555nm';...
'RRS670','RS reflectance at 670nm';...
'SAL','Salinity';...
'SECCHI_DEPTH','Secchi Depth';...
'SPEED_OF_SOUND','SPEED_OF_SOUND';...
'SPM','Suspended particulate matter';...
'SW_RAD','Surface Solar Irradiance';...
'SW_RAD_max','Surface Solar Irradiance (max)';...
'SW_RAD_min','Surface Solar Irradiance (min)';...
'SW_RAD_std','Surface Solar Irradiance (std)';...
'SprTp','Peak Directional Wave Spread';...
'Synechococcus','Synechococcus';...
'TEMP','Temperature';...
'TPAR_sf','Daily Surface Photosynthetically Active Photon Flux';...
'TSOLAR_sf','Daily Solar Irradiance';...
'TSSinorganic','TSSinorganic';...
'TSSorganic','TSSorganic';...
'Tilt','Tilt';...
'UCUR','UCUR (eastward velocity)';...
'VCUR','VCUR (northward velocity)';...
'Viola','Viola';...
'W10','Wind Speed';...
'WAVE_DIRECTION_sea','Mean Sea Wave Direction';...
'WAVE_DIRECTION_swell','Mean Swell Wave Direction';...
'WAVE_PERIOD_sea','Mean Sea Wave Period';...
'WAVE_PERIOD_swell','Mean Swell Wave Period';...
'WAVE_SPREAD','Mean Directional Wave Spread';...
'WAVE_SPREAD_sea','Mean Directional Sea Wave Spread';...
'WAVE_SPREAD_swell','Mean Directional Swell Wave Spread';...
'WCUR','WCUR';...
'WIND_DIR','Wind Direction';...
'WIND_DIR_std','Wind Direction (std)';...
'WIND_SPEED_min','Wind Speed (min)';...
'WL_398_uW','Spectral Radiative Flux (WL - 398µW)';...
'WL_398_umol','Spectral Photon Flux (WL - 398µmol)';...
'WL_448_uW','Spectral Radiative Flux (WL - 448µW)';...
'WL_448_umol','Spectral Photon Flux (WL - 448µmol)';...
'WL_470_uW','Spectral Radiative Flux (WL - 470µW)';...
'WL_470_umol','Spectral Photon Flux (WL - 470µmol)';...
'WL_524_uW','Spectral Radiative Flux (WL - 524µW)';...
'WL_524_umol','Spectral Photon Flux (WL - 524µmol)';...
'WL_554_uW','Spectral Radiative Flux (WL - 554µW)';...
'WL_554_umol','Spectral Photon Flux (WL - 554µmol)';...
'WL_590_uW','Spectral Radiative Flux (WL - 590µW)';...
'WL_590_umol','Spectral Photon Flux (WL - 590µmol)';...
'WL_628_uW','Spectral Radiative Flux (WL - 628µW)';...
'WL_628_umol','Spectral Photon Flux (WL - 628µmol)';...
'WL_656_uW','Spectral Radiative Flux (WL - 656µW)';...
'WL_656_umol','Spectral Photon Flux (WL - 656µmol)';...
'WL_699_uW','Spectral Radiative Flux (WL - 699µW)';...
'WL_699_umol','Spectral Photon Flux (WL - 699µmol)';...
'WQ_CAR_DIC','Dissolved Inorganic Carbon';...
'WQ_CAR_PH','pH';...
'WQ_DIAG_CAR_ALK','Total Alkalinity';...
'WQ_DIAG_MAC_PAR','Photosynthetically Active Radiation';...
'WQ_DIAG_OAS_IRR_BAND_1','Spectral Radiative Flux (WL - 410W)';...
'WQ_DIAG_OAS_IRR_BAND_2','Spectral Radiative Flux (WL - 440W)';...
'WQ_DIAG_OAS_IRR_BAND_3','Spectral Radiative Flux (WL - 490W)';...
'WQ_DIAG_OAS_IRR_BAND_4','Spectral Radiative Flux (WL - 510W)';...
'WQ_DIAG_OAS_IRR_BAND_5','Spectral Radiative Flux (WL - 550W)';...
'WQ_DIAG_OAS_IRR_BAND_6','Spectral Radiative Flux (WL - 590W)';...
'WQ_DIAG_OAS_IRR_BAND_7','Spectral Radiative Flux (WL - 635W)';...
'WQ_DIAG_OAS_IRR_BAND_8','Spectral Radiative Flux (WL - 660W)';...
'WQ_DIAG_OAS_IRR_BAND_9','Spectral Radiative Flux (WL - 700W)';...
'WQ_DIAG_OGM_CDOM','Chromophoric DOM';...
'WQ_DIAG_OGM_CDOM','Colored Dissolved Organic Matter';...
'WQ_DIAG_OXY_SAT','O2 Saturation';...
'WQ_DIAG_PHY_CHRYSO','Chrysophyta';...
'WQ_DIAG_PHY_CHRYSO_MALLOMONAS_AKROKOMOS','Mallomonas akrokomos';...
'WQ_DIAG_PHY_CRYPTO','Cryptophyta';...
'WQ_DIAG_PHY_DIATOM','Bacillariophyta';...
'WQ_DIAG_PHY_DINO','Dinophyta';...
'WQ_DIAG_PHY_EUGLE','Euglenophyta';...
'WQ_DIAG_PHY_GRN','Chlorophyta';...
'WQ_DIAG_PHY_OCHRO','Ochrophyta';...
'WQ_DIAG_PHY_TCHLA','Chlorophyll-a';...
'WQ_DIAG_PHY_TCHLB','Chlorophyll-b';...
'WQ_DIAG_PHY_TCHLC','Chlorophyll-c';...
'WQ_DIAG_TOT_TKN','Total Kjeldahl Nitrogen';...
'WQ_DIAG_TOT_TN','Total Nitrogen';...
'WQ_DIAG_TOT_TP','Total Phosphorus';...
'WQ_DIAG_TOT_TSS','Total Suspended Solids';...
'WQ_DIAG_TOT_TURBIDITY','Turbidity';...
'WQ_DIAG_ZOO_TZOO','Zooplankton';...
'WQ_GEO_FEII','Dissolved Iron';...
'WQ_GEO_TCU','Copper';...
'WQ_GEO_TNI','Nickel';...
'WQ_GEO_TPB','Lead';...
'WQ_GEO_TZN','Zinc';...
'WQ_NIT_AMM','Ammonium';...
'WQ_NIT_NIT','Nitrate';...
'WQ_OGM_DOC','Dissolved Organic Carbon';...
'WQ_OGM_DOC','Dissolved Organic Carbon Non-Purgeable';...
'WQ_OGM_DON','Dissolved Organic Nitrogen';...
'WQ_OGM_DOP','Dissolved Organic Phosphorus';...
'WQ_OGM_POC','Particulate Organic Carbon';...
'WQ_OXY_OXY','Dissolved Oxygen';...
'WQ_PHS_FRP','Filterable Reactive Phosphate';...
'WQ_SIL_RSI','Reactive Silica';...
'WVDIR','Peak Wave Direction';...
'WVHT','Significant Wave Height';...
'WVHT_sea','Significant Sea Wave Height';...
'WVHT_swell','Significant Swell Wave Height';...
'WVPER','Peak Wave Period';...
'Zea','Zea';...
'fluorescence','Fluorescence';...
'light_attenuation_coefficient','Light Attenuation Coefficient';...
'logger_temperature','Logger Temperature';...
'npp','Net Primary Productivity';...
'nppv','Total Primary Production of Phyto';...
'phaeophytin_a','Phaeophytin-a';...
'phyc','Phytoplankton';...
'posidonia_sinuosa_above_ground_biomass','Posidonia Sinuosa Above Ground Biomass';...
'posidonia_sinuosa_below_ground_biomass','Posidonia Sinuosa Below Ground Biomass';...
'posidonia_sinuosa_count','Posidonia Sinuosa Count';...
'posidonia_sinuosa_dry_weight','Posidonia Sinuosa Dry Weight';...
'posidonia_sinuosa_total_biomass','Posidonia Sinuosa Total Biomass';...
'spco2','Surface Partial Pressure of CO2';...
'surface_photosynthetically_active_photon_flux','Surface Photosynthetically Active Photon Flux';...
};

timeseries.start_plot_ID = 1;
timeseries.end_plot_ID = 203;
